feat: наконец закончить проект.
Sardiand/java-shareit pull request #1
Opened 2023-08-06 12:17 UTC by Sardiand

2023-08-06 20:15 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-06 20:15 UTC, FanaticFiz commented on pom.xml
> +		</dependency>
Хорошей практикой будет указать кодировку
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2023-08-06 20:15 UTC, FanaticFiz commented on pom.xml
> +		</dependency>
Я советую всем соблюдать некий порядок при объявлении зависимостей.
Сначала "главный" spring все его зависимости и всё о нём.
Потом по степени "тяжеловестности" остальные зависимости. Ну и у меня в проекте, например, последними идёт еще одна секция наши собственные библиотеки/модули/контракты.

2023-08-06 20:15 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Тут в аннотации можно объединить несколько классов исключений, чтобы не плодить одинаковые методы.

2023-08-06 20:15 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        return items.values().stream().filter(item -> (StringUtils.containsIgnoreCase(item.getName(), request) ||
Даже если код помещается в одну строку, при использовании цепочки вызовов, лучше выделять каждую осмысленную операцию на новую строку.

```
        return items.values().stream()
                    .filter(item -> containsIgnoreCase(item.getName(), request) || 
                            containsIgnoreCase(item.getDescription(), request))
                    .filter(Item::getAvailable)
                    .collect(Collectors.toList());
```

2023-08-06 20:15 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    Item createItem(long userId, ItemDto itemDto);
Методы не висят в воздухе!
Поэтому нет нужды в них повторять название сущности, например: `ItemService.createItem()`

Получается масло-масляное! 

Лучше: `ItemService.create()` `ItemService.update()`

2023-08-06 20:15 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +    Item findById(long itemId);
Применить бы тут `Optional`, попробуешь?
При одиночной выборке - очень удачно вписывается всегда.

2023-08-06 20:15 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            ConflictException exp = new ConflictException("Пользователь с указанным адресом электронной почты уже существует.");
Тогда вот так, нужно давать подробности и в лог и в сообщение.

```
            String message = String.format("Пользователь с email: %s уже существует.", userDto.getEmail());
            
            log.error(message);
            throw new ConflictException(message);
```

2023-08-07 12:35 UTC, Sardiand commented on pom.xml
> +		</dependency>
Не знал о таком. Поставил в properties.
А вот про порядок с зависимостями Spring всё ясно, а вот какие более "тяжеловесные" зависимости, то тут я полный профан, пока ещё не пониманию всё. Если какие-то "мелкие" библиотеки ещё понятны, то, например, с lombok мне сложно понять, насколько он тяжеловесен.

2023-08-07 12:37 UTC, Sardiand commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Согласен, объединил их в первом методе по обработке BadRequest.

2023-08-07 12:37 UTC, Sardiand commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        return items.values().stream().filter(item -> (StringUtils.containsIgnoreCase(item.getName(), request) ||
Понял, запомню.

2023-08-07 12:39 UTC, Sardiand commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    Item createItem(long userId, ItemDto itemDto);
Вот у меня с этими названиями методов вечная беда... Хочется, чтобы их наименование отличалось в разных классах-сервисах, хотя интуитивно понимаю, что их не перепутать.

2023-08-07 12:39 UTC, Sardiand commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +    Item findById(long itemId);
Сделал. Также под это дело переделал выброс ошибок.

2023-08-07 12:40 UTC, Sardiand commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            ConflictException exp = new ConflictException("Пользователь с указанным адресом электронной почты уже существует.");
Сделал немного по-другому, как в других ошибках.

2023-08-07 18:15 UTC, FanaticFiz approved these changes

2023-08-07 18:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    Item createItem(long userId, ItemDto itemDto);
Наоборот, надо чтобы хотелось делать их одинаковыми, тогда можно будет обьединить все сервисы под оним интерфейсом.

2023-08-27 16:40 UTC, merged