Add bookings
Sardiand/java-shareit pull request #2
Opened 2023-08-27 16:38 UTC by Sardiand

2023-08-27 19:50 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-27 19:50 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            State convertedState = State.valueOf(state);
Что мешает сразу принимать как тип `State`?

`@RequestParam(defaultValue = "ALL") State state`

2023-08-27 19:50 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllCurrentByBooker_IdOrderByStartDesc(long userId, LocalDateTime now);
Когда ты пишешь кастомный Query тебе не нужно собирать такое название метода, ты можешь дать более человечное название методу.

2023-08-27 19:50 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        booking.setStatus(available ? Status.APPROVED : Status.REJECTED);
- Можно предварительно заимпортить статики и получить более приятный и читаемый код
- и есть еще хорошая практика делать отступ перед `retutn` - чтобы визуально отделить точку выхода.

```
        booking.setStatus(available ? APPROVED : REJECTED);
        
        return bookingRepository.save(booking);
    }
```

2023-08-27 19:50 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemRepository.findAllByOwner_id(userId)
Не верно - сначала выбирать из базы записи, а потом начинать их сортировать или еще хуже фильтровать.

Переложи это на плечи БД, получи сразу то что тебе нужно.

2023-08-27 19:50 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .filter(Item::getAvailable)
Вот тут ты фильтруешь, получив из БД - смотри предыдущий комент.

2023-08-27 19:50 UTC, FanaticFiz commented on src/main/resources/application.properties
> +spring.datasource.driverClassName=org.postgresql.Driver
Когда будем учиться писать файл свойств в `YAML` формате?
Ведь где это делать если не тут?

2023-08-27 19:50 UTC, FanaticFiz commented on src/test/java/ru/practicum/shareit/ShareItTests.java
> +  /*  private UserController userController;
?

2023-09-05 11:55 UTC, Sardiand commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            State convertedState = State.valueOf(state);
Согласен, пофиксил.

2023-09-05 11:55 UTC, Sardiand commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllCurrentByBooker_IdOrderByStartDesc(long userId, LocalDateTime now);
Понял) Скорректировал)

2023-09-05 11:56 UTC, Sardiand commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        booking.setStatus(available ? Status.APPROVED : Status.REJECTED);
Пофиксил.

2023-09-05 12:16 UTC, Sardiand commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .filter(Item::getAvailable)
Исправил.

2023-09-05 12:17 UTC, Sardiand commented on src/main/resources/application.properties
> +spring.datasource.driverClassName=org.postgresql.Driver
Комментарии убрать?

2023-09-05 12:19 UTC, Sardiand commented on src/test/java/ru/practicum/shareit/ShareItTests.java
> +  /*  private UserController userController;
Это старые тесты, когда работали с хранилищами. Удалять не стал, в следующем спринте заменю мок тестами.

2023-09-06 18:46 UTC, FanaticFiz commented on src/main/resources/application.properties
> +spring.datasource.driverClassName=org.postgresql.Driver
https://www.baeldung.com/spring-yaml

2023-09-06 18:46 UTC, FanaticFiz approved these changes

2023-09-06 19:49 UTC, merged