fix: done
Sardiand/java-shareit pull request #3
Opened 2023-10-09 01:03 UTC by Sardiand

2023-11-29 19:49 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-11-29 19:49 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        User user = userRepository.findById(userId).orElseThrow(() ->
Код лучше структурировать следующим образом.
- каждая новая операция перечисленная через `.` должна быть с новой строки
- `return` отделяем от основного кода пустой строкой

```
    public ItemRequestDto create(long userId, IncomingItemRequestDto dto) {
        User user = userRepository
                .findById(userId)
                .orElseThrow(() -> logError(new NotFoundException("User с id " + userId + " не найден.")));
        ItemRequest request = itemRequestRepository.save(toItemRequest(user, dto));

        return toItemRequestDto(request);
    }
```

2023-11-29 19:49 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        } else {
Обрати внимание - тут можно избежать лишней вложенности - не нужно писать `else`

2023-11-29 19:49 UTC, FanaticFiz commented on src/test/java/ru/practicum/shareit/json/BookingTest.java
> +        assertThat(result).extractingJsonPathNumberValue("$.id").satisfies(
Тот же подход и тут. 
Новая операция начинается с новой строки.

```
        assertThat(result).extractingJsonPathNumberValue("$.id")
                          .satisfies(number -> assertThat(number.longValue()).isEqualTo(booking.getId()));
```

2023-12-05 08:31 UTC, Sardiand commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        User user = userRepository.findById(userId).orElseThrow(() ->
Поправил.

2023-12-05 08:31 UTC, Sardiand commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        } else {
Поправил.

2023-12-05 08:31 UTC, Sardiand commented on src/test/java/ru/practicum/shareit/json/BookingTest.java
> +        assertThat(result).extractingJsonPathNumberValue("$.id").satisfies(
И тут тоже.

2023-12-05 09:29 UTC, FanaticFiz approved these changes

2023-12-06 18:10 UTC, merged